version: '2'
services:
    dtls-app:
        image: dtls
        environment:
            - _JAVA_OPTIONS=-Xmx512m -Xms256m
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:mysql://dtls-mysql:3306/dtls?useUnicode=true&characterEncoding=utf8&useSSL=false
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
            - SPRING_DATA_JEST_URI=http://dtls-elasticsearch:9200
        ports:
            - 8286:8286
    dtls-mysql:
        extends:
            file: mysql.yml
            service: dtls-mysql
    dtls-elasticsearch:
        extends:
            file: elasticsearch.yml
            service: dtls-elasticsearch
